version: "3.8"
services:
  ssh_gpg:
    build:
      context: .
      args:
        SSH_USER_PASSWORD: ${SSH_USER_PASSWORD}
        SSH_ADMIN_PASSWORD: ${SSH_ADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - 2222:22
    restart: unless-stopped

